#!/bin/bash

[ -z "$TEST_RUNNER" ] && warn "No test runner found" && exit 0

task="$TEST_RUNNER-cov"

! task_exists "$task" && 
warn "$task task not found. Defaulting to $DEFAULT_COV_TASK" && 
task="$DEFAULT_COV_TASK"

npx task "$task"
