#!/bin/bash

function f1 { is_on_npm && echo "npm-deploy"; }
function f2 { is_on_ghp && echo "github-pages-deploy"; }
function f3 { is_on_sls && echo "sls-deploy"; }

infer_tasks "deploy" "f1 f2 f3"

# function mapper { $1; unset $1; }
# tasks=$(map "f1 f2 f3" mapper)

# [ -z "$tasks" ] && warn "Unable to infer deploy task" && exit 0

# echo
# echo "The following tasks will be run:"

# function action { echo "• $1"; }
# for_each "$tasks" action

# ask_ok

# function action { npx task "$1"; }
# for_each "$tasks" action




# tasks=()

# is_on_npm && tasks+=("npm-deploy")
# is_on_ghp && tasks+=("github-pages-deploy")
# is_on_sls && tasks+=("sls-deploy")

# [ ${#tasks[@]} = 0 ] && warn "Unable to infer ${BOLD}deploy${NORM} task" && exit 0

# echo
# echo "The following tasks will be run:"

# function action { echo "• $1"; }
# for_each "${tasks[@]}" action

# ask_ok

# function action { npx task "$1"; }
# for_each "${tasks[@]}" action
