#!/bin/bash

tasks=()

is_on_npm && tasks+=("npm-deploy")
is_on_ghp && tasks+=("github-pages-deploy")
is_on_sls && tasks+=("sls-deploy")

[ ${#tasks[@]} = 0 ] && echo "Couldn't infer what to deploy" && exit 1

echo
echo "The following tasks will be run:"

function action { echo "• $1"; }
for_each "${tasks[@]}" action

ask_ok

function action { npx task "$1"; }
for_each "${tasks[@]}" action
