#!/bin/bash

# Not yet sure how I could infer these:
# @node-loader/babel

which -s "jq" || brew install "jq"
which -s "itermocil" || brew install "TomAnthony/brews/itermocil"

npm_install "" module-composer

npm_install -D module-indexgen npm-check-updates eslint husky

if [ -f "$README_TEMPLATE" ]; then
    npm_install -D ejs doctoc cloc
fi

if [ -f "$SERVER" ]; then
    npm_install -D nodemon
    npm_install "" express cors ajv ajv-formats
fi

if [ -f "$SERVERLESS_CONFIG" ]; then
    npm_install -D serverless aws-sdk
fi

if has_dev_dependency "react"; then
    npm_install -D @babel/core @babel/preset-react
fi

if has_dev_dependency "@babel/core"; then
    npm_install -D @babel/preset-env @babel/node
fi

if has_dev_dependency "jest"; then
    npm_install -D jest-environment-jsdom
fi

if has_dev_dependency "eslint"; then
    function mapper { echo "eslint-plugin-$1"; }
    packages=$(OUTSEP=" " list_map "$ESLINT_PLUGINS" mapper)
    npm_install -D "$packages"
fi

exit 0
