#!/bin/bash
  
cat << EOF > "$ITERMOCIL_CONFIG" 
windows:
  - name: $PACKAGE_NAME
    root: $(pwd)
    layout: tiled
    panes:
EOF

IFS="$SEP"; tasks=($DEV_TASKS); unset IFS

function action {
    cat << EOF >> "$ITERMOCIL_CONFIG" 
        - commands:
            - nvm use
            - npx task $1
EOF
}

for_each "$DEV_TASKS" action
