#!/bin/bash

export NODE_VERSION="22.19.0"

export BARREL_PATHS="./src/node | ./tests"

export COV_BRANCHES="0"
export COV_LINES="0"
export COV_FUNCTIONS="0"
export COV_STATEMENTS="0"

export BFF_URL__LOCAL="local"
export BFF_URL__TEST="test"

export TEST_RUNNER="module-testrunner"
