#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

npx c8 \
    --all \
    --src "$SRC" \
    --reporter=text-summary \
    --reporter=json-summary \
    --reporter=lcov \
    "$@" \
    npx task test
