#!/bin/bash

[ $(has_dev_dependency "react") = "true" ] && npx task babel-config-gen
[ $(has_dev_dependency "jest") = "true" ] && npx task jest-config-gen
[ $(has_dev_dependency "eslint") = "true" ] && npx task eslint-config-gen

exit 0
