#!/bin/bash

tasks=()

echo "Inferring whether to deploy NPM package..."
is_on_npm && tasks+=("npm-deploy")

echo "Inferring whether to deploy to GitHub Pages..."
is_on_ghp && tasks+=("github-pages-deploy")

echo "Inferring whether to deploy Serverless app..."
is_on_sls && tasks+=("sls-deploy")

[ ${#tasks[@]} = 0 ] && echo "Couldn't infer what to deploy" && exit 1

echo
echo "The following tasks will be run:"

function action { echo "• $1"; }
for_each "${tasks[@]}" action

ask_continue

for task_name in "${tasks[@]}"; do
    npx task "$task_name"
done
