#!/bin/bash

read -p "❓ Are you sure? " choice
case "$choice" in 
  y|Y ) ;;
  n|N ) echo "⚠️  Aborting..."; exit 0;;
  * ) echo "⚠️  Invalid input"; exit 1;;
esac

echo

[ $(is_on_npm) = "true" ] && npx task publish

[ $(is_on_ghp) = "true" ] && npx task dist-github-pages

[ $(is_on_sls) = "true" ] && sls deploy

exit 0
