#!/bin/bash

IFS=' | '; package_names=($NODE_MODULES_LINK_PACKAGES); unset IFS

rm -rf "$NODE_MODULES_LINKS"
mkdir -p "$NODE_MODULES_LINKS"

for n in "${package_names[@]}"; do
    target="$NODE_MODULES/$n"
    link="$NODE_MODULES_LINKS/$n"
    [ -d "$target" ] && ln -s "$target" "$link"
done
