#!/bin/bash

. $TASK_LIBRARY_SRC/load-task-vars

npx task dist

[ ! -z "$GITHUB_PAGES_CNAME" ]] && cat "$GITHUB_PAGES_CNAME" > "$DIST/CNAME"

rm -rf "$GITHUB_PAGES_PATH"
mkdir -p "$GITHUB_PAGES_PATH"
cp -a "$DIST/" "$GITHUB_PAGES_PATH"
