#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

GITIGNORE=".gitignore"

cat <<END >> $GITIGNORE
node_modules
/*cache
/*output
/build
/coverage
/metrics
/temp
/config.*
/itermocil.yml
/.vscode
.DS_Store
END

sort -u -o $GITIGNORE $GITIGNORE

git add "$GITIGNORE"
