#!/bin/bash
  
cat <<END >> $GIT_IGNORE
node_modules
/*cache
/*output
/build
/coverage
/dist
/metrics
/temp
/config.*
/itermocil.yml
/.vscode
/.serverless
/.nyc_output
.DS_Store
npm-debug.log
END

sort -u -o $GIT_IGNORE $GIT_IGNORE

git add "$GIT_IGNORE"
