#!/bin/bash

cat > "$INDEX_HTML" <<EOF
<head>
<title>$INDEX_HTML_TITLE</title>
<meta name="title" content="$INDEX_HTML_TITLE">
<meta name="description" content="$INDEX_HTML_DESCRIPTION">
<meta name="author" content="$INDEX_HTML_AUTHOR">
<meta name="url" content="$INDEX_HTML_URL">
<script type="module" src="./app.js"></script>
</head>
<body>
<div id="app"></div>
</body>
EOF
