#!/bin/bash

cat > "$INDEX_HTML" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<title>$INDEX_HTML_TITLE</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="title" content="$INDEX_HTML_TITLE">
<meta name="description" content="$INDEX_HTML_DESCRIPTION">
<meta name="author" content="$INDEX_HTML_AUTHOR">
<meta name="url" content="$INDEX_HTML_URL">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Shadows+Into+Light" />
<script type="text/JavaScript" src="https://mattriley.github.io/webcomponents.js"></script>
<script type="module" src="./app.js" defer></script>
$INDEX_HTML_HEAD
</head>
<body>
<div id="app"></div>
</body>
</html>
EOF
