#!/bin/bash

# Not yet sure how I could infer these:
# @node-loader/babel

npm_install "" module-composer
npm_install -D module-indexgen npm-check-updates eslint husky

if [ -f "$README_TEMPLATE" ]; then
    npm_install -D ejs doctoc cloc
fi

if [ -f "$SERVER" ]; then
    npm_install -D nodemon
fi

if [ -f "$SERVERLESS_CONFIG" ]; then
    npm_install -D serverless aws-sdk
fi

if has_dev_dependency "react"; then
    npm_install -D @babel/core @babel/preset-react
fi

if has_dev_dependency "@babel/core"; then
    npm_install -D @babel/preset-env @babel/node
fi

if has_dev_dependency "jest"; then
    npm_install -D jest-environment-jsdom
fi

if has_dev_dependency "eslint"; then
    IFS="$SEP"; plugins=($ESLINT_PLUGINS); unset IFS
    install_list=()

    for name in "${plugins[@]}"; do
        install_list+=("eslint-plugin-$name")
    done

    [[ ${#install_list[@]} -gt 0 ]] && npm_install -D "${install_list[@]}"
fi

exit 0
