#!/bin/bash

npm i -D "eslint" "husky"

if [ ! -z $TEST_RUNNER ]; then
    npm -D i "$TEST_RUNNER"
fi

# "@node-loader/babel"

if has_any_dependency "react"; then
    npm -D i \
        "@babel/core" \
        "@babel/preset-react"
fi

if has_any_dependency "@babel/core"; then
    npm -D i \
        "@babel/preset-env" \
        "@babel/node"
fi

if has_any_dependency "react" && has_any_dependency "eslint"; then
    npm -D i "eslint-plugin-react"
fi

if has_any_dependency "jest"; then
    npm -D i "jest-environment-jsdom"
fi

if has_any_dependency "jest" && has_any_dependency "eslint"; then
    npm -D i "eslint-plugin-jest"
fi

if [ -f "$README_TEMPLATE" ]; then
    npm -D i "doctoc" "cloc"
fi
