#!/bin/bash

if $(has_dev_dependency "react") = "true"; then
    
    npm -D i \
        "@babel/core" \
        "@babel/preset-env" \
        "@babel/preset-react" \
        "@node-loader/babel" \
        "eslint-plugin-react"

fi

if $(has_dev_dependency "jest") = "true"; then

    npm -D i \
        "jest-environment-jsdom" \
        "eslint-plugin-jest"

fi
