#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

npx task itermocil-install   

cat > "itermocil.yml" <<EOF
windows:
  - name: $PROJECT_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
EOF

for TASK_NAME in "${ITERMOCIL_TASKS[@]}"
do
TASK_FILE=$(taskfile $TASK_NAME)
if [[ ! -z "$TASK_FILE" ]]; then
  cat >> "itermocil.yml" <<EOF
      - commands:
        - nvm use
        - $TASK_FILE
EOF
  fi
done

itermocil
