#!/bin/bash
  
npx task itermocil-install   

cat > "$ITERMOCIL_CONFIG" <<EOF
windows:
  - name: $PACKAGE_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
EOF

for TASK_NAME in "${ITERMOCIL_TASKS[@]}"
do
TASK_FILE=$(taskfile $TASK_NAME)
if [[ ! -z "$TASK_FILE" ]]; then
  cat >> "$ITERMOCIL_CONFIG" <<EOF
      - commands:
        - nvm use
        - npx task $TASK_NAME
EOF
  fi
done

itermocil
