#!/bin/bash

npx task babel-config-gen
npx task jest-config-gen

NODE_OPTIONS="--experimental-vm-modules" \
npx jest test \
    --roots "$TESTS" \
    --testMatch "<rootDir>/$TEST_PATTERN" \
    --passWithNoTests \
    "$@"
