#!/bin/bash
  
shebang="#!/bin/bash\n\n"
args="\"\$@\""

mkdir -p "$TASKS"

echo -e "${shebang}npx task jest-test $args" > "$TASKS/test"
echo -e "${shebang}npx task jest-test-watch $args" > "$TASKS/test-watch"
echo -e "${shebang}npx task jest-cov $args" > "$TASKS/test-cov"
echo -e "${shebang}npx task jest-cov-check $args" > "$TASKS/test-cov-check"
