#!/bin/bash
  
npx -p npm-check-updates \
    ncu -u

echo "Running npm install..."

npm i

task_link="./node_modules/.bin/task"

[ ! -L ${task_link} ] && echo "⚠️  ${task_link} not found. Running npm install again..." && npm i

[ ! -L ${task_link} ] && echo "⚠️  ${task_link} still not found"

exit 0
