#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

PARCEL_COMMAND="${1:-build}"

rm -rf "$DIST"
mkdir -p "$DIST"
cp -a "$STATIC/." "$DIST/"

npx parcel "$PARCEL_COMMAND" \
    "$INDEX_HTML" \
    --public-url "$DIST_PUBLIC_URL" \
    --dist-dir "$DIST"
