#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

PARCEL_COMMAND="${1:-build}"
[[ $PARCEL_COMMAND = 'build' ]] && PUBLIC_URL="$DIST_PUBLIC_URL" || PUBLIC_URL="/"

rsync -au --delete "$STATIC" "$DIST"  

npx task index-html-gen

npx parcel "$PARCEL_COMMAND" \
    "$INDEX_HTML" \
    --public-url "$PUBLIC_URL" \
    --dist-dir "$DIST"
