#!/bin/bash

set -e

npx task babel-config-gen
npx task jest-config-gen
npx task lint-config-gen
npx task code-gen
npx task lint
npx task cov-check
npx task sloc
npx task metrics-summary
npx task readme-gen
npx task gitignore-gen
npx task package-gen
