#!/bin/bash

set -e

npx task package-gen
npx task gitignore-gen
npx task config-gen
npx task code-gen
npx task lint --fix
npx task cov-check
npx task sloc
npx task metrics-summary
npx task readme-gen

git add .
