#!/bin/bash

# All

[ "$1" = "--all" ] && echo "$VARS" && exit 0

# Selected

IFS="$SEP"; var_names=($PRINT_VARS); unset IFS

echo

for var_name in "${var_names[@]}"; do
    [ $var_name = "STAGE" ] && [ ${!var_name} = 'prod' ] && style="$RED" || style="$BOLD"
    echo "$var_name=${style}${!var_name}${NORM}"
done

vars_printed=${#var_names[@]}
vars_total=$(echo -n "$VARS" | grep -c '^')

echo
echo "${vars_printed} of ${vars_total} task vars displayed"
echo
