#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

npx react-scripts test \
    --roots "$TESTS" \
    --testMatch "<rootDir>/$TEST_PATTERN" \
    --watchAll false \
    --silent \
    --passWithNoTests \
    "$@"
