#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

npx task react-scripts-cov \
    --roots "$SRC" \
    --collectCoverageFrom "<rootDir>/$SRC/**" \
    --coverageThreshold="{\"global\":{\"branches\":$COV_BRANCHES,\"functions\":$COV_FUNCTIONS,\"lines\":$COV_LINES,\"statements\":$COV_STATEMENTS}}"
