#!/bin/bash
  
set -e

[ ! -f "$README_TEMPLATE" ] && exit 0

OPTIONS=()

if grep -q "@node-loader/babel" "./package.json"; then
    OPTIONS+=" --experimental-loader @node-loader/babel"
fi

node ${OPTIONS[@]} "$README_GEN" > "$README"

npx task doctoc

git add "$README"
