#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

npx task tap-cov \
    --no-browser \
    --check-coverage \
    --branches $COV_BRANCHES \
    --lines $COV_LINES \
    --functions $COV_FUNCTIONS \
    --statements $COV_STATEMENTS
