#!/bin/bash
  
. $TASK_LIBRARY_SRC/load-task-vars

node \
    --experimental-specifier-resolution=node \
    --input-type=module \
    - < $TASK_LIBRARY_NODE_TASKS/zora-testrunner.mjs "$TEST_PATTERN"
