#!/bin/bash

[ -z "$PACKAGE_NAME" ] && PACKAGE_NAME=$(npm run env | grep "npm_package_name" | awk -F "=" '{print $2}')
[ -z "$DISPLAY_NAME" ] && [ "$PACKAGE_NAME" ] && DISPLAY_NAME="$PACKAGE_NAME"

[ -z "$WEB_BASE_PATH" ] && WEB_BASE_PATH="/"
[ -z "$WEB_URL" ] && [ "$WEB_HOST_NAME" ] && [ "$WEB_BASE_PATH" ] && WEB_URL="https://$WEB_HOST_NAME$WEB_BASE_PATH"

[ -z "$ITERMOCIL_TASKS" ] && ITERMOCIL_TASKS="edit | test-watch | barrel-gen-watch | start"
[ -z "$TEST_WATCH_PATHS" ] && TEST_WATCH_PATHS="$SRC | $TESTS | $TEST_HELPERS"
[ -z "$ESLINT_PATHS" ] && ESLINT_PATHS="$SRC"

[ -z "$NPM_URL" ] && NPM_URL="https://www.npmjs.com/package/$PACKAGE_NAME"

[[ $(git config --get remote.origin.url) =~ github\.com:(.+)\/(.+)\.git$ ]]

[ -z "$GITHUB_USER_NAME" ] && [ ${BASH_REMATCH[1]} ] && GITHUB_USER_NAME=${BASH_REMATCH[1]}
[ -z "$GITHUB_REPO_NAME" ] && [ ${BASH_REMATCH[2]} ] && GITHUB_REPO_NAME=${BASH_REMATCH[2]}
[ -z "$GITHUB_REPO_PATH" ] && GITHUB_REPO_PATH="$GITHUB_USER_NAME/$GITHUB_REPO_NAME"
[ -z "$GITHUB_USER_URL" ] && GITHUB_USER_URL="https://github.com/$GITHUB_USER_NAME"
[ -z "$GITHUB_REPO_URL" ] && GITHUB_REPO_URL="$GITHUB_USER_URL/$GITHUB_REPO_NAME"
[ -z "$GITHUB_ISSUES_URL" ] && GITHUB_ISSUES_URL="$GITHUB_REPO_URL/issues"
[ -z "$GITHUB_PAGES_URL" ] && GITHUB_PAGES_URL="https://$GITHUB_USER_NAME.github.io/$GITHUB_REPO_NAME"
[ -z "$GITHUB_PAGES_CNAME" ] && [[ ! "$WEB_HOST_NAME" == *".github.io" ]] && GITHUB_PAGES_CNAME="$WEB_HOST_NAME"

[ -z "$ISSUES_URL" ] && ISSUES_URL="$GITHUB_ISSUES_URL"
[ -z "$ISSUES_EMAIL" ] && ISSUES_EMAIL="$AUTHOR_EMAIL"
[ -z "$SOURCE_CODE_URL" ] && SOURCE_CODE_URL="$GITHUB_REPO_URL"

[ -z "$INDEX_HTML_TITLE" ] && INDEX_HTML_TITLE="$DISPLAY_NAME"
[ -z "$INDEX_HTML_DESCRIPTION" ] && INDEX_HTML_DESCRIPTION="$(package description)"
[ -z "$INDEX_HTML_AUTHOR" ] && INDEX_HTML_AUTHOR="$AUTHOR_NAME"
[ -z "$INDEX_HTML_URL" ] && [ "$WEB_URL" ] && INDEX_HTML_URL="$WEB_URL"

[ -z "$README_BASE_URL" ] && README_BASE_URL="$GITHUB_REPO_URL"
[ -z "$README_GEN" ] && README_GEN="$TASK_LIBRARY_NODE_TASKS/readme-gen.js"
