#!/bin/bash

export PRINT_VARS="DISPLAY_NAME | STAGE"

export STAGE
export TARGET
export NODE_ENV
export BABEL_ENV
export VERSION_DATE=$(date)

export PACKAGE="./package.json"
export PACKAGE_NAME=$(package name)
export DISPLAY_NAME
export AUTHOR_NAME
export AUTHOR_EMAIL
export AUTHOR_URL

export WEB_HOST_NAME
export WEB_BASE_PATH
export WEB_URL

export TASKS="./tasks"
export TASK_VARS="./task-vars"

export NODE_MODULES="./node_modules"
export NODE_MODULES_LINKS="./node_modules_links"
export NODE_MODULES_LINK_PACKAGES="module-composer | module-indexgen | task-library"

export ITERMOCIL_CONFIG="./itermocil.yml"
export ITERMOCIL_TASKS="edit | test-watch | barrel-gen-watch | start"

export GIT_IGNORE="./.gitignore"
export GIT_BRANCH=$(git branch --show-current)

export SRC="./src"
export MODULES="$SRC/modules"
export BARREL_PATHS="$MODULES"

export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.{js,mjs}"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS
export TEST_RUNNER

export COVERAGE="./coverage"
export COVERAGE_JSON_SUMMARY="$COVERAGE/coverage-summary.json"

export METRICS="./metrics"
export METRICS_COV="$METRICS/cov.json"
export METRICS_LOC="$METRICS/loc.json"
export METRICS_SUMMARY="$METRICS/metrics-summary.json"

export BABEL_CONFIG="./babel.config.json"
export JEST_CONFIG="./jest.config.json"
export ESLINT_CONFIG="./.eslintrc.json"
export ESLINT_PATHS

[[ $(git config --get remote.origin.url) =~ github\.com:(.+)\/(.+)\.git$ ]]

export GITHUB_USER_NAME
export GITHUB_REPO_NAME
export GITHUB_REPO_PATH
export GITHUB_USER_URL
export GITHUB_REPO_URL
export GITHUB_ISSUES_URL
export GITHUB_PAGES_URL
export GITHUB_PAGES_PATH
export GITHUB_PAGES_CNAME

export ISSUES_URL
export ISSUES_EMAIL
export SOURCE_CODE_URL

export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export README_TITLE
export README_BASE_URL
export README_GEN

export INDEX_HTML
export INDEX_HTML_URL
export INDEX_HTML_TITLE
export INDEX_HTML_DESCRIPTION
export INDEX_HTML_AUTHOR
export INDEX_HTML_HEAD

export STATIC
export DATA
export DIST="./dist-$STAGE"

export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
