#!/bin/bash

export VERSION_DATE=$(date)

export PACKAGE="./package.json"
export PACKAGE_NAME=$(package name)
export DISPLAY_NAME
export AUTHOR_NAME
export AUTHOR_EMAIL
export AUTHOR_URL

export WEB_HOST_NAME
export WEB_BASE_PATH
export WEB_URL

export TASKS="./tasks"
export TASK_VARS="./task-vars"

export NODE_MODULES="./node_modules"
export NODE_MODULES_LINKS="./node_modules_links"
export NODE_MODULES_LINK_PACKAGES="module-composer | module-indexgen | task-library"

export ITERMOCIL_CONFIG="./itermocil.yml"
export ITERMOCIL_TASKS="edit | test-watch | barrel-gen-watch | start"

export GIT_IGNORE="./.gitignore"
export GIT_BRANCH=$(git branch --show-current)

export SRC="./src"
export MODULES="$SRC/modules"
export BARREL_PATHS="$MODULES"

export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.{js,mjs}"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS

export COVERAGE="./coverage"
export COVERAGE_JSON_SUMMARY="$COVERAGE/coverage-summary.json"

export METRICS="./metrics"
export METRICS_COV="$METRICS/cov.json"
export METRICS_LOC="$METRICS/loc.json"
export METRICS_SUMMARY="$METRICS/metrics-summary.json"

export ESLINT_CONFIG="./.eslintrc"
export ESLINT_PATHS

[[ $(git config --get remote.origin.url) =~ github\.com:(.+)\/(.+)\.git$ ]]

export GITHUB_USER_NAME   && [ -z "$GITHUB_USER_NAME" ]   && [ ${BASH_REMATCH[1]} ] && GITHUB_USER_NAME=${BASH_REMATCH[1]}
export GITHUB_REPO_NAME   && [ -z "$GITHUB_REPO_NAME" ]   && [ ${BASH_REMATCH[2]} ] && GITHUB_REPO_NAME=${BASH_REMATCH[2]}
export GITHUB_REPO_PATH   && [ -z "$GITHUB_REPO_PATH" ]   && GITHUB_REPO_PATH="$GITHUB_USER_NAME/$GITHUB_REPO_NAME"
export GITHUB_USER_URL    && [ -z "$GITHUB_USER_URL" ]    && GITHUB_USER_URL="https://github.com/$GITHUB_USER_NAME"
export GITHUB_REPO_URL    && [ -z "$GITHUB_REPO_URL" ]    && GITHUB_REPO_URL="$GITHUB_USER_URL/$GITHUB_REPO_NAME"
export GITHUB_ISSUES_URL  && [ -z "$GITHUB_ISSUES_URL" ]  && GITHUB_ISSUES_URL="$GITHUB_REPO_URL/issues"
export GITHUB_PAGES_URL   && [ -z "$GITHUB_PAGES_URL" ]   && GITHUB_PAGES_URL="https://$GITHUB_USER_NAME.github.io/$GITHUB_REPO_NAME"
export GITHUB_PAGES_PATH  && [ -z "$GITHUB_PAGES_PATH" ]  && GITHUB_PAGES_PATH="./docs"
export GITHUB_PAGES_CNAME

export ISSUES_URL
export ISSUES_EMAIL
export SOURCE_CODE_URL

export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export README_BASE_URL
export README_GEN

export INDEX_HTML="$SRC/index.html"
export INDEX_HTML_URL
export INDEX_HTML_TITLE
export INDEX_HTML_DESCRIPTION
export INDEX_HTML_AUTHOR
export INDEX_HTML_HEAD

export STATIC="./static"
export DATA="./data"
export DIST="./dist-$STAGE"

export BABEL_CONFIG="./babel.config.json"
export JEST_CONFIG="./jest.config.json"

export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
