#!/bin/bash

export VERSION_DATE=$(date)

# origin_url=$(git config --get remote.origin.url)

# export GITHUB_USER_NAME=$(node )

export PACKAGE_NAME=$(package "name.split('/').pop()")
export DISPLAY_NAME

export WEB_HOST_NAME
export WEB_BASE_PATH
export WEB_URL

export TASKS="./tasks"
export TASK_VARS="./task-vars"

export ITERMOCIL_CONFIG="./itermocil.yml"
export ITERMOCIL_TASKS

export GIT_IGNORE="./.gitignore"
export GIT_BRANCH=$(git branch --show-current)

export SRC="./src"
export MODULES="$SRC/modules"
export BARREL_PATHS="$MODULES"

export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.js"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS

export COVERAGE="./coverage"
export COVERAGE_JSON_SUMMARY="$COVERAGE/coverage-summary.json"

export METRICS="./metrics"
export METRICS_COV="$METRICS/cov.json"
export METRICS_LOC="$METRICS/loc.json"
export METRICS_SUMMARY="$METRICS/metrics-summary.json"

export ESLINT_CONFIG="./.eslintrc"
export ESLINT_PATHS

export NPM_URL

export GITHUB_USER_NAME
export GITHUB_REPO_PATH 
export GITHUB_USER_URL
export GITHUB_REPO_URL
export GITHUB_ISSUES_URL
export GITHUB_PAGES_URL 
export GITHUB_PAGES_CNAME
export GITHUB_PAGES_PATH="./docs"

export ISSUES_URL
export ISSUES_EMAIL
export SOURCE_CODE_URL

export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export README_BASE_URL
export README_GEN

export INDEX_HTML="$SRC/index.html"
export INDEX_HTML_URL
export INDEX_HTML_TITLE
export INDEX_HTML_DESCRIPTION
export INDEX_HTML_AUTHOR
export INDEX_HTML_HEAD

export STATIC="./static"
export DIST="./dist"
export DATA="./data"

export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
