#!/bin/bash

export TASKS="./tasks"
export TASK_VARS="./task-vars"

export ITERMOCIL_CONFIG="./itermocil.yml"
export ITERMOCIL_TASKS="edit | test-watch | barrel-gen-watch | start"

export PACKAGE_NAME=$(package "name.split('/').pop()")
export INTERNAL_NAME=
export EXTERNAL_NAME=

export GIT_IGNORE="./.gitignore"
export GIT_BRANCH=$(git branch --show-current)

export SRC="./src"
export MODULES="$SRC/modules"
export BARREL_PATHS="$MODULES"

export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.js"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS="$SRC | $TESTS | $TEST_HELPERS"

export COVERAGE="./coverage"
export COVERAGE_JSON_SUMMARY="$COVERAGE/coverage-summary.json"

export METRICS="./metrics"
export METRICS_COV="$METRICS/cov.json"
export METRICS_LOC="$METRICS/loc.json"
export METRICS_SUMMARY="$METRICS/metrics-summary.json"

export ESLINT_CONFIG="./.eslintrc"
export ESLINT_PATHS="$SRC"

export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export README_BASE_URL=$(package homepage)
export README_GEN="$TASK_LIBRARY_NODE_TASKS/readme-gen.js"

export INDEX_HTML="$SRC/index.html"
export INDEX_HTML_URL=
export INDEX_HTML_TITLE=
export INDEX_HTML_DESCRIPTION="$(package description)"
export INDEX_HTML_AUTHOR="$(package author)"
export INDEX_HTML_HEAD=

export WEB_HOST_NAME=
export WEB_BASE_PATH="/"

export STATIC="./static"
export DIST="./dist"

export GITHUB_PAGES_PATH="./docs"
export GITHUB_PAGES_CNAME=

export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
