#!/bin/bash

export TASK_PATHS=("./tasks")
export ITERMOCIL_TASKS=("edit" "test-watch" "barrel-gen-watch" "start")

export PACKAGE_NAME=$(package "name.split('/').pop()")
export PROJECT_NAME="$PACKAGE_NAME"
export GIT_BRANCH=$(git branch --show-current)

export SRC="./src"
export MODULES="$SRC/modules"
export BARREL_PATHS=("$MODULES")

export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.js"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS=("$SRC" "$TESTS" "$TEST_HELPERS")

export COVERAGE="./coverage"
export COVERAGE_JSON_SUMMARY="$COVERAGE/coverage-summary.json"

export METRICS="./metrics"
export METRICS_COV="$METRICS/cov.json"
export METRICS_LOC="$METRICS/loc.json"
export METRICS_SUMMARY="$METRICS/metrics-summary.json"

export ESLINT_PATHS=("$SRC" "$TESTS")

export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export README_BASE_URL=$(package homepage)
export README_GEN="$TASK_LIBRARY_NODE_TASKS/readme-gen.js"

export INDEX_HTML="$SRC/index.html"
export INDEX_HTML_URL=""
export INDEX_HTML_TITLE="$PROJECT_NAME"
export INDEX_HTML_DESCRIPTION="$(package description)"
export INDEX_HTML_AUTHOR="$(package author)"

export STATIC="./static"
export DIST="./dist"
export DIST_PUBLIC_URL="/$PACKAGE_NAME/"
export GITHUB_PAGES_PATH="./docs"

export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
