#!/bin/bash

function package() {
    echo $(node -e "console.log(require('./package.json').$1)")
}

function nowInMs() { 
    echo $(node -e 'console.log(Date.now())') ; 
}

. $TASK_LIBRARY_SRC/default-task-vars
. ./task-vars

export TASK_LIBRARY_TASK_PATHS=(${TASK_PATHS[@]} "$TASK_LIBRARY_TASKS")

function taskfile() {
    TASK_NAME="$1"
    for TASK_PATH in ${TASK_LIBRARY_TASK_PATHS[@]}; do [ -f "$TASK_PATH/$TASK_NAME" ] && TASK_FILE="$TASK_PATH/$TASK_NAME" && break; done
    echo "$TASK_FILE"
}
