#!/bin/bash
  
. ./task-vars

[ ! -f "$README_TEMPLATE" ] && exit 0

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

OPTIONS=(
    "--input-type=module"
    "--experimental-specifier-resolution=node"
)

if grep -q "@node-loader/babel" "./package.json"; then
    OPTIONS+="--experimental-loader @node-loader/babel"
fi

node \
    ${OPTIONS[@]} \
    - "$README_TEMPLATE" < $SCRIPT_DIR/readme-file-generator.js > "$README"

npx doctoc \
    --maxlevel=2 \
    "$README"
