#!/bin/bash
  
. ./task-vars

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

node \
    --experimental-specifier-resolution=node \
    --input-type=module \
    - < $SCRIPT_DIR/zora-testrunner.js "$TEST_PATTERN"
